### ISSUE TITLE
How should the use of collaborative editing tools in remote meetings be addressed in this document?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/remote-meetings#13]
At the 6 April 2022 RQTF teleconference, the issue of how the use of collaborative editing tools during remote meetings should be addressed in this document was discussed.

We currently mention collaborative editing tools in section 4.1.2, noting the relevance of the Authoring Tool Accessibility Guidelines. That is, any editing tool used in a meeting should conform to ATAG. That's the full extent of our acknowledgment of the issue in the present draft.

It was suggested at the Task Force meeting that we should add an Editor's Note on this issue prior to publication of the next Public Working Draft, and that some aspects of the problem may be taken up in revising Accessibility of Remote Meetings further.

It was also suggested that the issues associated with making collaborative editing software accessible could usefully be treated elsewhere (e.g., as a separate work item, potentially leading to a Task Force deliverable). However, it was also recognized that some issues (e.g., the complexities of attending to the real-time interactions in the meeting while attempting to perform collaborative editing tasks - potentially involving multiple parties who are simultaneously editing a document) could usefully be mentioned here.

**Comment by sehollier** [comment]
Issue addressed in second PDW. And collaborative tools work progressing into wiki. Closing issue.
