### ISSUE TITLE
EOWG Feedback on Remote Meetings Document

### ISSUE THREAD

**Issue by bakkenb** [w3c/remote-meetings#16]
Sorry for the late response on this. EOWG did meet and review the Remote Meetings Draft. Here is a link to the public survey with comments and recommendations: [https://www.w3.org/2002/09/wbs/35532/Remote-Mtgs-1/results#xq2](https://www.w3.org/2002/09/wbs/35532/Remote-Mtgs-1/results#xq2)

**Comment by JaninaSajka** [comment]
I would request that EO clarify its specific request as individual github issues, and do so against the forthcoming public working draft. As Jason notes, it's unclear what are EO consensus positions, and what individual comments. Both are welcome, of course, but our process would want each in an individual github issue. Lastly, we would welcome EO using content from this document wherever and however it sees fit in w3.org/wai resources. We do, however, believe it's important to publish a single document that lays out all the issues and approaches identified following several years research and editing in a single document. Again, if I'm misunderstanding the request here, please clarify. We'll happily cooperate to maximize the utility of this work.

**Comment by sehollier** [comment]
Second PDW is now available. Would welcome Github issues based on the latest drive.

**Comment by jasonjgw** [comment]
My understanding from informal communications that have taken place in the past week is as follows.

* The Education and Outreach Working Group currently has no substantive comments on the text of the most recent public working draft of the document.
* The Education and Outreach Working Group is satisfied with assurances from the Research Questions Task Force that material from this document may be cited, repurposed or reused by EO or other W3C/WAI groups, as appropriate, subsequently to its publication as a W3C Working Group Note.
* Thus, the EO review is complete at this point, and Accessibility of Remote Meetings may be considered for transition to W3C Note status.

In view of the above, I think we can close this issue. If any of the foregoing is inaccurate, please reopen the issue.
