### ISSUE TITLE
References should be made consistent.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/remote-meetings#5]
Some references in this document are given as links that refer directly to the external resources.

Other references are provided as bibliography entries.

I think we should make them all consistent - probably as bibliography entries.

**Comment by sehollier** [comment]
Agree completely

**Comment by jasonjgw** [comment]
I created Pull Request #12 to address this issue. Comments and corrections would be welcome.

I left the references in the Resources section as is, since it's meant to be separate from the bibliography. I also left links to external documents in place throughout the text, but added cross-references to the bibliography as needed.

**Comment by sehollier** [comment]
Reviewed and looks great, support this request.
