### ISSUE TITLE
The focus of section 4 is unclear, and parts of it may better belong in section 3.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/remote-meetings#6]
The introduction to section 4 refers to materials used in remote meetings (e.g., presentations, documents, etc. - we should probably mention meeting notes as well).

However, section 4 goes on to discuss WCAG success criteria applicable to live content (i.e., the real-time interaction among meeting participants). this is rather confusing.

The accessibility of the interaction among participants is usually a function of the meeting platform, so perhaps parts of this material should be moved into section 3 instead, and section 4 should purely focus on presentations, documents, notes, and associated materials.

As it stands, the current organization is very confusing and unclear.

Comments on what should be done are welcome.

**Comment by sehollier** [comment]
Would welcome this change and help with the edits to make it more clear within the sections.

**Comment by sehollier** [comment]
Support this request, Thank you.
